# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 828b4288d48f2587cde3cdd88bab59dcf94688efb1d201db86cc7197fcffeca7dac207260d84f1632e216c5f38153f66a9509d699278583b999244a11c45b84e

test:
  secret_key_base: 95fe97aecb0dd80549a847d9b644564da82cf640f2c6ec58854ba55845d2bfc5a64569d5ba4cdf81bb69b99f09adadf5e549aa368083c7e499eb9fa76a325bde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
